micronaut:
  application:
    name: micronautCrudDemo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    schema-generate: CREATE_DROP
    dialect: POSTGRES
r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: POSTGRES
      url: r2dbc:postgresql://localhost:5432/postgres
      username: postgres
      password: ''
jpa.default.properties.hibernate.hbm2ddl.auto: update
